name: 'Dependabot Haskell Stack'
description: 'Update Haskell Stack dependencies'
author: 'Steve Mao'

# Define your inputs here.
inputs:
  stack-yaml:
    description: 'Override project stack.yaml file (overrides any STACK_YAML environment variable).'
    default: './stack.yaml'

# Define your outputs here.
outputs:
  resolver:
    description: 'The latest resolver'

runs:
  using: node20
  main: dist/index.js
