name: 'Dependabot Haskell Stack'
description: 'Update Haskell Stack dependencies'
author: 'Steve Mao'
branding:
  icon: 'chevrons-up'
  color: 'purple'

# Define your inputs here.
inputs:
  stack-yaml:
    description: 'Override project stack.yaml file (overrides any STACK_YAML environment variable).'
    default: './stack.yaml'
  resolver-major:
    description: 'Bump major version of the resoler (LTS only).'
    default: 'true'
  ghc:
    description: 'Specify the GHC version that the resolver should use.'

# Define your outputs here.
outputs:
  previous-resolver:
    description: 'The previous resolver'
  new-resolver:
    description: 'The new resolver'

runs:
  using: node20
  main: dist/index.js
